### ISSUE TITLE
It tells me there is a trojan virus with this download, how nice

### ISSUE THREAD

**Issue by Spacecow90** [carpikes/MayaCrasher#1]

**Comment by carpikes** [comment]
Well, it's not a Trojan. The source code is available and you can build it by yourself to check.
Anyway, this program it copies itself into Maya and make it crash triggering the crash handler, which is a technique similar to what some viruses do.

I should setup a CI so that CircleCI can build the executable by itself, so that it can even be more trusted.

EDIT: I uploaded the v1.0 on VirusTotal, so that it gets scanned by all antiviruses out there and the result is 100% safe: https://www.virustotal.com/gui/url/23f7f116f8e8a276435283dccc97f836668a2f7de839a85281e8d34f3d57a353
Which antivirus tells you that this is a trojan?
